#include "MainWindow.hpp"
#include "CelestialBodyPanel.hpp"
#include "TestSettings.hpp"
#include "Moderator.hpp"
#include "SolarSystem.hpp"
#include "CelestialBody.hpp"
#include "BaseException.hpp"
#include "FileManager.hpp"
#include "QtPlotReceiver.hpp"
#include "OrbitRenderer.hpp"
#include <QApplication>
#include <QPlainTextEdit>
#include <QTreeWidget>
#include <QMdiArea>
#include <QMdiSubWindow>
#include <QLineEdit>
#include <QComboBox>
#include <QListWidget>
#include <QTabWidget>
#include <QLabel>
#include <QPushButton>
#include <QDialogButtonBox>
#include <QFileDialog>
#include <QColorDialog>
#include <QMessageBox>
#include <QAction>
#include <QTimer>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QImage>
#include <QElapsedTimer>
#include <QThread>
#include <iostream>
#include <cmath>
#include <limits>
#include <stdexcept>
static void require(bool value,const char *message) { if (!value) throw std::runtime_error(message); }
static QString bytes(const QString &path) { QFile file(path); require(file.open(QIODevice::ReadOnly),"Body report missing"); return QString::fromUtf8(file.readAll()); }
static CelestialBody *body(const QString &name) { return dynamic_cast<CelestialBody *>(Moderator::Instance()->GetConfiguredObject(name.toStdString())); }
static QMap<QString,QString> state(const QString &name) { QMap<QString,QString> values; for (const auto &field:celestialBodyFields(*body(name))) values.insert(field.name,field.value); return values; }
static void events(int milliseconds=250) { QElapsedTimer elapsed; elapsed.start(); while (elapsed.elapsed()<milliseconds) { QApplication::processEvents(); QThread::msleep(5); } }
static void capture(QWidget &widget,const QString &path) { if (!path.isEmpty()) { events(); require(widget.grab().save(path),"Body panel capture failed"); } }
template<class Open,class Inspect> static void modal(QWidget &owner,Open open,Inspect inspect)
{
   bool inspected=false; std::exception_ptr failure; QTimer timer; timer.setSingleShot(true);
   QObject::connect(&timer,&QTimer::timeout,&owner,[&] { auto *dialog=qobject_cast<QDialog *>(QApplication::activeModalWidget()); try { require(dialog,"Expected modal missing"); inspected=true; inspect(dialog); } catch (...) { failure=std::current_exception(); } if (dialog && dialog->isVisible()) dialog->reject(); });
   timer.start(0); open(); timer.stop(); if (failure) std::rethrow_exception(failure); require(inspected,"Modal did not open");
}
static CelestialBodyPanel *open(MainWindow &window,const QString &name)
{
   auto *tree=window.findChild<QTreeWidget *>("Resources"); const auto items=tree->findItems(name,Qt::MatchExactly|Qt::MatchRecursive); require(items.size()==1,"Body resource entry missing"); tree->itemDoubleClicked(items.first(),0); QApplication::processEvents();
   auto *workspace=window.findChild<QMdiArea *>("workspace"); require(workspace->activeSubWindow(),"Body MDI window missing"); auto *panel=dynamic_cast<CelestialBodyPanel *>(workspace->activeSubWindow()->widget()); require(panel,"Body editor missing"); return panel;
}
static void close(MainWindow &window) { for (auto *child:window.findChild<QMdiArea *>("workspace")->subWindowList()) if (auto *panel=dynamic_cast<EditablePanel *>(child->widget())) { panel->discardChanges(); child->close(); } QApplication::processEvents(); }
static QLineEdit *edit(CelestialBodyPanel &panel,const QString &field) { auto *value=panel.findChild<QLineEdit *>("body_"+field); require(value,"Body value control missing"); return value; }
static void apply(CelestialBodyPanel &panel) { panel.findChild<QDialogButtonBox *>()->button(QDialogButtonBox::Apply)->click(); require(!panel.hasChanges(),qPrintable(panel.findChild<QLabel *>("bodyStatus")->text())); QApplication::processEvents(); }
static const PlotCurve &curve(MainWindow &window,const QString &name) { const auto model=window.plotReceiver()->model("Orb"); require(model!=nullptr,"Body plot data missing"); for (const auto &entry:model->curves) if (entry.name==name) return entry; throw std::runtime_error("Body plot curve missing"); }
static QImage render(MainWindow &window,const QString &path)
{
   if (QApplication::platformName()=="offscreen") return {};
   auto model=std::make_shared<PlotModel>(*window.plotReceiver()->model("Orb")); OrbitRenderer renderer(model); renderer.resize(600,600); renderer.show(); renderer.setView(1,0,0,{},std::numeric_limits<quint64>::max()); events(500); auto image=renderer.captureImage(); require(!image.isNull(),"Native body rendering unavailable"); if (!path.isEmpty()) require(image.save(path),"Native body render capture failed"); renderer.close(); events(50); return image;
}
static int changedPixels(const QImage &first,const QImage &second)
{
   require(first.size()==second.size(),"Native rendering changed image dimensions"); int count=0;
   for (int y=0;y<first.height();++y) for (int x=0;x<first.width();++x) if (first.pixel(x,y)!=second.pixel(x,y)) ++count;
   return count;
}
int main(int argc,char **argv)
{
   QApplication::setAttribute(Qt::AA_DontUseNativeDialogs); QApplication app(argc,argv); app.setOrganizationName("GMATTests"); app.setApplicationName("QtBodies");
   try {
      TestSettings settings; QTemporaryDir files; require(files.isValid() && argc>1,"Body fixtures unavailable"); const auto startup=QFileInfo(argv[1]).absoluteFilePath(),captures=argc>2 ? QString::fromLocal8Bit(argv[2]) : QString(); QDir::setCurrent(QFileInfo(startup).absolutePath());
      MainWindow window; window.show(); require(window.initialize(startup),"Body runtime initialization failed"); auto *editor=window.findChild<QPlainTextEdit *>("scriptEditor"); const auto report=files.filePath("bodies.txt"),saved=files.filePath("bodies ü.script");
      const QString resources="% body GUI round trip Δ\nCreate Spacecraft Sat;\nCreate ForceModel FM;\nFM.PrimaryBodies = {};\nFM.PointMasses = {Earth};\nCreate Propagator Prop;\nProp.FM = FM;\nCreate ReportFile Values;\nValues.Filename = '"+report+"';\nValues.WriteHeaders = false;\nValues.Precision = 16;\nCreate OrbitView Orb;\nOrb.Add = {Sat, Earth};\nOrb.ViewPointReference = Earth;\nOrb.ViewPointVector = [0 0 25000];\nOrb.ViewDirection = Earth;\nOrb.EnableStars = Off;\nOrb.EnableConstellations = Off;\nOrb.Axes = Off;\nOrb.Grid = Off;\n";
      const QString mission="BeginMissionSequence; % preserve all commands\nPropagate 'Body run' Prop(Sat) {Sat.ElapsedSecs = 120}; % keep propagation\nReport Values Sat.EarthMJ2000Eq.X Sat.EarthMJ2000Eq.Y Sat.EarthMJ2000Eq.Z Sat.Earth.Altitude Sat.EarthFixed.X Sat.EarthFixed.Y Sat.EarthFixed.Z;\n";
      const auto original=resources+mission; editor->setPlainText(original); require(window.saveScriptTo(saved) && window.runMission()==MainWindow::RunResult::Completed,"Body mission failed"); const auto baselineReport=bytes(report); auto *panel=open(window,"Earth"); require(!panel->hasChanges(),"New body editor already dirty"); const auto originalState=state("Earth"); auto *tabs=panel->findChild<QTabWidget *>("bodyPages"); require(tabs && tabs->count()==4 && tabs->tabText(0)=="Properties" && tabs->tabText(1)=="Orbit" && tabs->tabText(2)=="Orientation" && tabs->tabText(3)=="Visualization","wx body pages missing");
      require(panel->findChild<QComboBox *>("body_PosVelSource") && !panel->findChild<QComboBox *>("body_PosVelSource")->isEnabled() && edit(*panel,"CentralBody")->isReadOnly() && edit(*panel,"SpinAxisRAConstant")->isReadOnly(),"Built-in source/central body/pole constants not protected");
      edit(*panel,"Mu")->setText("400000"); edit(*panel,"EquatorialRadius")->setText("6400"); edit(*panel,"Flattening")->setText("0.01"); tabs->setCurrentIndex(2); edit(*panel,"NutationUpdateInterval")->setText("10");
      require(panel->hasChanges() && state("Earth")==originalState && editor->toPlainText()==original,"Pending body settings changed engine/source"); capture(*panel->parentWidget(),captures.isEmpty() ? QString() : captures+".orientation.png"); tabs->setCurrentIndex(0); capture(*panel->parentWidget(),captures.isEmpty() ? QString() : captures+".properties.png");
      modal(*panel,[&] { panel->findChild<QPushButton *>("showScript")->click(); },[](QDialog *dialog) { require(!dialog->findChild<QPlainTextEdit *>("inspectionText")->toPlainText().contains("6400"),"Applied body preview contains pending radius"); }); apply(*panel); const auto configured=editor->toPlainText(); require(configured.endsWith(mission) && !configured.contains("Create Planet Earth"),"Built-in body edit created/replaced body or changed mission"); editor->undo(); require(editor->toPlainText()==original,"Body Undo not exact/atomic"); editor->redo(); require(editor->toPlainText()==configured,"Body Redo not exact"); require(window.runMission()==MainWindow::RunResult::Completed,"GUI physical body mission failed"); const auto physicalReport=bytes(report); require(physicalReport!=baselineReport && curve(window,"Earth").radius==6400,"Physical properties did not affect report/viewer radius");
      require(window.saveScriptTo(saved) && window.loadScript(saved) && window.runMission()==MainWindow::RunResult::Completed && bytes(report)==physicalReport,"Body Unicode save/reopen changed calculations");
      const QString explicitPhysical="Earth.Mu = 400000;\nEarth.EquatorialRadius = 6400;\nEarth.Flattening = 0.01;\nEarth.NutationUpdateInterval = 10;\n"; editor->setPlainText(explicitPhysical+original); require(window.runMission()==MainWindow::RunResult::Completed && bytes(report)==physicalReport,"GUI/raw-script physical body calculations differ");
      // Native orbit scene changes from a texture, then a body model/pose.
      const auto texture=files.filePath("texture ü.png"),modelFile=files.filePath("shape ü.obj"); QImage map(64,32,QImage::Format_RGB32); for (int y=0;y<map.height();++y) for (int x=0;x<map.width();++x) map.setPixelColor(x,y,(x/8+y/8)%2 ? QColor(245,25,35) : QColor(20,220,245)); require(map.save(texture),"Texture fixture failed");
      { QFile file(modelFile); require(file.open(QIODevice::WriteOnly),"OBJ fixture failed"); file.write("v -1000 -700 -300\nv 1000 -700 -300\nv 0 1500 -300\nv 0 0 1900\nf 1 3 2\nf 1 2 4\nf 2 3 4\nf 3 1 4\n"); }
      const auto baseImage=render(window,{}); panel=open(window,"Earth"); tabs=panel->findChild<QTabWidget *>("bodyPages"); tabs->setCurrentIndex(3); const auto beforeAppearance=editor->toPlainText();
      modal(*panel,[&] { panel->findChild<QPushButton *>("bodyChoose_TextureMapFileName")->click(); },[](QDialog *dialog) { require(qobject_cast<QFileDialog *>(dialog),"Texture chooser missing"); }); require(!panel->hasChanges(),"Texture picker Cancel changed field");
      modal(*panel,[&] { panel->findChild<QPushButton *>("bodyChoose_TextureMapFileName")->click(); },[&](QDialog *dialog) { auto *chooser=qobject_cast<QFileDialog *>(dialog); chooser->selectFile(texture); static_cast<QDialog *>(chooser)->accept(); }); require(edit(*panel,"TextureMapFileName")->text()==texture && !panel->findChild<QLabel *>("bodyTexturePreview")->pixmap().isNull(),"Texture selection/preview failed");
      require(editor->toPlainText()==beforeAppearance && state("Earth").value("TextureMapFileName")!=texture,"Pending texture changed model/script"); capture(*panel->parentWidget(),captures.isEmpty() ? QString() : captures+".visualization.png"); apply(*panel); require(window.runMission()==MainWindow::RunResult::Completed && bytes(report)==physicalReport && QFileInfo(curve(window,"Earth").texturePath).canonicalFilePath()==QFileInfo(texture).canonicalFilePath(),"Texture edit changed calculations or did not reach viewer"); const auto textureImage=render(window,captures.isEmpty() ? QString() : captures+".texture.png"); if (!baseImage.isNull()) require(changedPixels(baseImage,textureImage)>2000,"Texture did not change the rendered body surface");
      panel=open(window,"Earth"); tabs=panel->findChild<QTabWidget *>("bodyPages"); tabs->setCurrentIndex(3); modal(*panel,[&] { panel->findChild<QPushButton *>("bodyChoose_3DModelFile")->click(); },[&](QDialog *dialog) { auto *chooser=qobject_cast<QFileDialog *>(dialog); chooser->selectFile(modelFile); static_cast<QDialog *>(chooser)->accept(); }); edit(*panel,"3DModelScale")->setText("3"); edit(*panel,"3DModelOffsetX")->setText("0.1"); edit(*panel,"3DModelRotationY")->setText("35");
      modal(*panel,[&] { panel->findChild<QPushButton *>("bodyChoose_OrbitColor")->click(); },[](QDialog *dialog) { require(qobject_cast<QColorDialog *>(dialog),"Body color dialog missing"); });
      modal(*panel,[&] { panel->findChild<QPushButton *>("bodyChoose_OrbitColor")->click(); },[](QDialog *dialog) { auto *color=qobject_cast<QColorDialog *>(dialog); color->setCurrentColor(QColor(220,150,20)); color->accept(); }); apply(*panel); require(window.runMission()==MainWindow::RunResult::Completed && bytes(report)==physicalReport,"Model/color changes affected calculation"); const auto &displayed=curve(window,"Earth"); require(displayed.modelPath==modelFile && displayed.modelScale==3 && displayed.modelOffset[0]==0.1 && displayed.modelRotation[1]==35 && displayed.color==QColor(220,150,20),"Body model/pose/color did not reach orbit scene"); const auto modelImage=render(window,captures.isEmpty() ? QString() : captures+".model.png"); if (!textureImage.isNull()) require(changedPixels(modelImage,textureImage)>2000,"Body model/pose did not change native body rendering");
      require(window.saveScriptTo(saved) && window.loadScript(saved) && window.runMission()==MainWindow::RunResult::Completed && bytes(report)==physicalReport && curve(window,"Earth").modelPath==modelFile,"Model/texture save/reopen failed");
      auto commentedAppearance=editor->toPlainText(); commentedAppearance.replace("Earth.3DModelScale = 3;","Earth.3DModelScale = 3; % preserve model scale explanation"); editor->setPlainText(commentedAppearance); require(window.buildScript(),"Commented body appearance fixture failed");
      require(window.applyResourceChanges("Earth",{{"3DModelScale","4"}},commentedAppearance).isEmpty(),"Repeated model-scale edit failed"); const auto repeatedAppearance=editor->toPlainText(); require(repeatedAppearance.count("Earth.3DModelScale =")==1 && repeatedAppearance.contains("% preserve model scale explanation") && repeatedAppearance.endsWith(mission),"Digit-prefixed body property replacement lost comments/mission or duplicated assignments");
      require(window.applyResourceChanges("Earth",{{"3DModelScale","4"}},repeatedAppearance).isEmpty() && editor->toPlainText()==repeatedAppearance,"Repeated body Apply changed identical source"); require(window.applyResourceChanges("Earth",{{"3DModelScale","3"}},repeatedAppearance).isEmpty() && window.runMission()==MainWindow::RunResult::Completed && bytes(report)==physicalReport,"Repeated appearance edits changed calculation");
      const auto valid=editor->toPlainText(); const auto validBody=state("Earth"); const auto malformed=files.filePath("bad image.txt"); { QFile file(malformed); require(file.open(QIODevice::WriteOnly),"Bad file fixture failed"); file.write("not an image or model"); }
      for (const auto &bad:QList<QMap<QString,QString>>{{{"Mu","0"}},{{"EquatorialRadius","-1"}},{{"Flattening","-0.1"}},{{"NutationUpdateInterval","nan"}},{{"NutationUpdateInterval","-1"}},{{"SpinAxisRAConstant","10"}},{{"PosVelSource","SPICE"}},{{"CentralBody","Mars"}},{{"RotationDataSource","SPICE"}},{{"3DModelScale","0"}},{{"3DModelScale","1001"}},{{"3DModelOffsetY","3.6"}},{{"3DModelRotationZ","181"}},{{"3DModelFile",malformed}},{{"TextureMapFileName",malformed}},{{"TextureMapFileName",files.filePath("missing.png")}},{{"NAIFId","1.5"}}}) require(!window.applyResourceChanges("Earth",bad,valid).isEmpty() && editor->toPlainText()==valid && state("Earth")==validBody,"Invalid body field changed model/script");
      panel=open(window,"Earth"); edit(*panel,"Mu")->setText("nan"); panel->findChild<QDialogButtonBox *>()->button(QDialogButtonBox::Apply)->click(); require(panel->hasChanges() && !panel->findChild<QLabel *>("bodyStatus")->text().isEmpty(),"Invalid GUI value discarded pending edit"); edit(*panel,"Mu")->setText("400001"); apply(*panel); require(body("Earth")->GetRealParameter(body("Earth")->GetParameterID("Mu"))==400001,"Body invalid-edit correction failed");
      require(window.applyResourceChanges("Earth",{{"Mu","400000"},{"3DModelFile",""},{"TextureMapFileName",""}},editor->toPlainText()).isEmpty() && window.runMission()==MainWindow::RunResult::Completed && bytes(report)==physicalReport && curve(window,"Earth").modelPath.isEmpty() && QFileInfo(curve(window,"Earth").texturePath).canonicalFilePath()!=QFileInfo(texture).canonicalFilePath(),"Clear model/default texture failed or changed calculation"); close(window);
      // Create and configure a user-defined body with the actual New resource
      // dialog. Ceres data, poles and frame reports exercise its orbit/rotation.
      editor->setPlainText(original); require(window.buildScript(),"User body baseline failed"); modal(window,[&] { window.findChild<QAction *>("createResource")->trigger(); },[](QDialog *dialog) { auto *type=dialog->findChild<QComboBox *>("resourceType"); require(type->findText("Asteroid")>=0,"Asteroid missing from New resource"); type->setCurrentText("Asteroid"); dialog->findChild<QLineEdit *>("resourceName")->setText("Ceres"); dialog->findChild<QDialogButtonBox *>()->button(QDialogButtonBox::Ok)->click(); }); require(body("Ceres") && body("Ceres")->IsUserDefined(),"GUI user body creation failed"); panel=open(window,"Ceres"); require(!panel->hasChanges() && !edit(*panel,"SpinAxisRAConstant")->isReadOnly() && !edit(*panel,"NAIFId")->isReadOnly(),"User body source/pole/ID controls wrong"); tabs=panel->findChild<QTabWidget *>("bodyPages"); tabs->setCurrentIndex(1);
      const auto ceresKernel=files.filePath("ceres ü.bsp"); require(QFile::copy(QFileInfo(startup).absolutePath()+"/../data/planetary_ephem/spk/ceres_1900_2100.bsp",ceresKernel),"Ceres SPK unavailable"); auto *kernels=panel->findChild<QListWidget *>("body_OrbitSpiceKernelName"); require(kernels,"Ceres SPK editor missing"); modal(*panel,[&] { panel->findChild<QPushButton *>("bodyAdd_OrbitSpiceKernelName")->click(); },[&](QDialog *dialog) { auto *picker=qobject_cast<QFileDialog *>(dialog); picker->selectFile(ceresKernel); static_cast<QDialog *>(picker)->accept(); }); require(kernels->count()==1 && kernels->item(0)->text()==ceresKernel,"Ceres SPK selection failed"); edit(*panel,"NAIFId")->setText("2000001"); edit(*panel,"Mu")->setText("63"); edit(*panel,"EquatorialRadius")->setText("470"); edit(*panel,"Flattening")->setText("0.03"); edit(*panel,"SpinAxisRAConstant")->setText("30"); edit(*panel,"SpinAxisDECConstant")->setText("70"); edit(*panel,"RotationConstant")->setText("20"); edit(*panel,"RotationRate")->setText("40"); capture(*panel->parentWidget(),captures.isEmpty() ? QString() : captures+".orbit.png"); apply(*panel);
      const QString frames="Create CoordinateSystem CeresFrame;\nCeresFrame.Origin = Ceres;\nCeresFrame.Axes = MJ2000Eq;\nCreate CoordinateSystem CeresFixed;\nCeresFixed.Origin = Ceres;\nCeresFixed.Axes = BodyFixed;\n";
      auto userMission=editor->toPlainText(); userMission.insert(userMission.indexOf("BeginMissionSequence"),frames); userMission.replace("Sat.EarthFixed.Z;","Sat.EarthFixed.Z Sat.CeresFrame.X Sat.CeresFrame.Y Sat.CeresFrame.Z Sat.CeresFixed.X Sat.CeresFixed.Y Sat.CeresFixed.Z;"); editor->setPlainText(userMission); require(window.runMission()==MainWindow::RunResult::Completed,"GUI Ceres ephemeris/orientation mission failed"); const auto userReport=bytes(report); require(window.saveScriptTo(saved) && window.loadScript(saved) && window.runMission()==MainWindow::RunResult::Completed && bytes(report)==userReport,"Ceres Unicode save/reopen changed reports");
      const QString explicitCeres="Create Asteroid Ceres;\nCeres.NAIFId = 2000001;\nCeres.OrbitSpiceKernelName = {'"+ceresKernel+"'};\nCeres.Mu = 63;\nCeres.EquatorialRadius = 470;\nCeres.Flattening = 0.03;\nCeres.SpinAxisRAConstant = 30;\nCeres.SpinAxisDECConstant = 70;\nCeres.RotationConstant = 20;\nCeres.RotationRate = 40;\n"; auto reference=explicitCeres+frames+original; reference.replace("Sat.EarthFixed.Z;","Sat.EarthFixed.Z Sat.CeresFrame.X Sat.CeresFrame.Y Sat.CeresFrame.Z Sat.CeresFixed.X Sat.CeresFixed.Y Sat.CeresFixed.Z;"); editor->setPlainText(reference); require(window.runMission()==MainWindow::RunResult::Completed && bytes(report)==userReport,"GUI/raw-script Ceres orbit/orientation reports differ");
      panel=open(window,"Ceres"); edit(*panel,"SpinAxisRAConstant")->setText("45"); apply(*panel); require(window.runMission()==MainWindow::RunResult::Completed && bytes(report)!=userReport,"Pole edit did not affect body-fixed frame report"); const auto rotated=bytes(report); reference.replace("Ceres.SpinAxisRAConstant = 30;","Ceres.SpinAxisRAConstant = 45;"); editor->setPlainText(reference); require(window.runMission()==MainWindow::RunResult::Completed && bytes(report)==rotated,"GUI/raw-script pole reports differ");
      const auto beforeInvalid=editor->toPlainText(); require(!window.applyResourceChanges("Ceres",{{"PosVelSource","DE405"}},beforeInvalid).isEmpty(),"Unsupported user body DE source accepted"); require(window.applyResourceChanges("Ceres",{{"NAIFId","-1234567"}},beforeInvalid).isEmpty(),"Unknown-ID fixture not accepted for runtime validation"); require(window.runMission()==MainWindow::RunResult::Failed,"Unknown SPICE body ID did not fail at execution"); require(window.applyResourceChanges("Ceres",{{"NAIFId","2000001"}},editor->toPlainText()).isEmpty() && window.runMission()==MainWindow::RunResult::Completed && bytes(report)==rotated,"SPICE body failure did not recover after ID correction");
      // PCK and FK lists use complete replacement, not append-only setters.
      // Exercise order, replacement/removal, kernel-type errors and an imported
      // SPICE rotation source through a body-fixed coordinate report.
      const auto pck=files.filePath("planetary ü.tpc"),pck2=files.filePath("planetary second.tpc"),fk=files.filePath("frame ü.tf"),fk2=files.filePath("frame second.tf");
      require(QFile::copy(QString::fromStdString(FileManager::Instance()->GetFullPathname("PLANETARY_PCK_FILE")),pck) && QFile::copy(pck,pck2),"PCK fixtures unavailable");
      auto writeFrame=[&](const QString &path,int angle) { QFile file(path); require(file.open(QIODevice::WriteOnly),"FK fixture unavailable"); const auto text=QString("KPL/FK\n\\begindata\nFRAME_CERES_TEST = 140001\nFRAME_140001_NAME = 'CERES_TEST'\nFRAME_140001_CLASS = 4\nFRAME_140001_CLASS_ID = 140001\nFRAME_140001_CENTER = 2000001\nTKFRAME_140001_RELATIVE = 'J2000'\nTKFRAME_140001_SPEC = 'ANGLES'\nTKFRAME_140001_UNITS = 'DEGREES'\nTKFRAME_140001_AXES = (3, 2, 1)\nTKFRAME_140001_ANGLES = (%1, 0, 0)\n\\begintext\n").arg(angle); file.write(text.toUtf8()); }; writeFrame(fk,15); writeFrame(fk2,45);
      auto addFile=[&](CelestialBodyPanel &panel,const QString &field,const QString &path) { modal(panel,[&] { panel.findChild<QPushButton *>("bodyAdd_"+field)->click(); },[&](QDialog *dialog) { auto *picker=qobject_cast<QFileDialog *>(dialog); require(picker,"Kernel chooser missing"); picker->selectFile(path); static_cast<QDialog *>(picker)->accept(); }); };
      panel=open(window,"Ceres"); tabs=panel->findChild<QTabWidget *>("bodyPages"); tabs->setCurrentIndex(0); auto *pcks=panel->findChild<QListWidget *>("body_PlanetarySpiceKernelName"); require(pcks && pcks->count()==0,"Unexpected Ceres PCK defaults"); modal(*panel,[&] { panel->findChild<QPushButton *>("bodyAdd_PlanetarySpiceKernelName")->click(); },[](QDialog *) {}); require(!panel->hasChanges(),"Kernel Add Cancel changed panel"); addFile(*panel,"PlanetarySpiceKernelName",pck); addFile(*panel,"PlanetarySpiceKernelName",pck2); pcks->setCurrentRow(1); panel->findChild<QPushButton *>("bodyUp_PlanetarySpiceKernelName")->click(); require(pcks->item(0)->text()==pck2,"PCK Up failed"); panel->findChild<QPushButton *>("bodyDown_PlanetarySpiceKernelName")->click(); require(pcks->item(1)->text()==pck2,"PCK Down failed"); panel->findChild<QPushButton *>("bodyRemove_PlanetarySpiceKernelName")->click(); require(pcks->count()==1 && pcks->item(0)->text()==pck,"PCK Remove failed");
      modal(*panel,[&] { panel->findChild<QPushButton *>("bodyReplace_PlanetarySpiceKernelName")->click(); },[&](QDialog *dialog) { auto *picker=qobject_cast<QFileDialog *>(dialog); picker->selectFile(pck2); static_cast<QDialog *>(picker)->accept(); }); require(pcks->item(0)->text()==pck2,"PCK Replace failed");
      tabs->setCurrentIndex(2); addFile(*panel,"FrameSpiceKernelName",fk); addFile(*panel,"FrameSpiceKernelName",fk2); edit(*panel,"SpiceFrameId")->setText("CERES_TEST"); const auto pendingKernelSource=editor->toPlainText(); const auto pendingKernelMission=pendingKernelSource.mid(pendingKernelSource.indexOf("BeginMissionSequence")); require(state("Ceres").value("FrameSpiceKernelName").isEmpty(),"Pending FK list changed body"); apply(*panel); require(state("Ceres").value("PlanetarySpiceKernelName")==pck2 && state("Ceres").value("FrameSpiceKernelName")==fk+"\n"+fk2 && editor->toPlainText().endsWith(pendingKernelMission),"Complete PCK/FK membership not applied"); require(window.runMission()==MainWindow::RunResult::Completed && bytes(report)==rotated,"Kernel metadata edit changed simplified-pole calculations");
      const auto validKernels=editor->toPlainText(),kernelReport=bytes(report); const auto kernelState=state("Ceres");
      for (const auto &bad:QList<QMap<QString,QString>>{{{"PlanetarySpiceKernelName",ceresKernel}},{{"FrameSpiceKernelName",pck2}},{{"OrbitSpiceKernelName",fk}},{{"FrameSpiceKernelName",files.filePath("missing.tf")}},{{"PlanetarySpiceKernelName",pck2+"\n"+pck2}}}) require(!window.applyResourceChanges("Ceres",bad,validKernels).isEmpty() && editor->toPlainText()==validKernels && state("Ceres")==kernelState,"Invalid kernel list changed source/body");
      auto imported=editor->toPlainText(); imported.insert(imported.indexOf("BeginMissionSequence"),"Ceres.RotationDataSource = SPICE;\n"); editor->setPlainText(imported); require(window.runMission()==MainWindow::RunResult::Completed,"Imported SPICE rotation with GUI FK/PCK settings failed"); const auto frameReport=bytes(report); require(frameReport!=kernelReport,"SPICE frame ID did not affect body-fixed report");
      const QString kernelSettings="Ceres.PlanetarySpiceKernelName = {'"+pck2+"'};\nCeres.FrameSpiceKernelName = {'"+fk+"', '"+fk2+"'};\nCeres.SpiceFrameId = 'CERES_TEST';\nCeres.RotationDataSource = SPICE;\n"; auto kernelReference=reference; kernelReference.insert(kernelReference.indexOf("BeginMissionSequence"),kernelSettings); editor->setPlainText(kernelReference); require(window.runMission()==MainWindow::RunResult::Completed && bytes(report)==frameReport,"GUI/raw-script kernel/frame reports differ");
      panel=open(window,"Ceres"); tabs=panel->findChild<QTabWidget *>("bodyPages"); tabs->setCurrentIndex(2); require(edit(*panel,"RotationDataSource")->text()=="SPICE" && edit(*panel,"RotationDataSource")->isReadOnly(),"Imported rotation source not displayed"); auto *fks=panel->findChild<QListWidget *>("body_FrameSpiceKernelName"); fks->setCurrentRow(1); panel->findChild<QPushButton *>("bodyUp_FrameSpiceKernelName")->click(); apply(*panel); require(window.runMission()==MainWindow::RunResult::Completed && bytes(report)!=frameReport,"FK order did not select the last loaded frame definition"); const auto orderedFrame=bytes(report); auto orderedReference=kernelReference; orderedReference.replace("{'"+fk+"', '"+fk2+"'}","{'"+fk2+"', '"+fk+"'}"); editor->setPlainText(orderedReference); require(window.runMission()==MainWindow::RunResult::Completed && bytes(report)==orderedFrame,"GUI/raw-script reordered frame reports differ"); require(window.saveScriptTo(saved) && window.loadScript(saved) && window.runMission()==MainWindow::RunResult::Completed && bytes(report)==orderedFrame,"Kernel order/rotation save/reopen failed");
      panel=open(window,"Ceres"); auto *spks=panel->findChild<QListWidget *>("body_OrbitSpiceKernelName"); spks->setCurrentRow(0); panel->findChild<QPushButton *>("bodyRemove_OrbitSpiceKernelName")->click(); apply(*panel); require(state("Ceres").value("OrbitSpiceKernelName").isEmpty() && window.runMission()==MainWindow::RunResult::Failed,"Cleared Ceres SPK did not remove membership/fail execution"); panel=open(window,"Ceres"); addFile(*panel,"OrbitSpiceKernelName",ceresKernel); apply(*panel); require(window.runMission()==MainWindow::RunResult::Completed && bytes(report)==orderedFrame,"Missing-SPK correction did not recover reports");
      close(window); editor->setPlainText(original); require(window.buildScript(),"Default body kernel removal fixture failed"); panel=open(window,"Luna"); auto *defaultPcks=panel->findChild<QListWidget *>("body_PlanetarySpiceKernelName"); require(defaultPcks && defaultPcks->count()>0,"Luna default kernel list missing"); defaultPcks->selectAll(); panel->findChild<QPushButton *>("bodyRemove_PlanetarySpiceKernelName")->click(); addFile(*panel,"PlanetarySpiceKernelName",pck2); apply(*panel); require(state("Luna").value("PlanetarySpiceKernelName")==pck2,"Default PCK replacement appended/retained startup membership");
      panel=open(window,"Luna"); defaultPcks=panel->findChild<QListWidget *>("body_PlanetarySpiceKernelName"); defaultPcks->selectAll(); panel->findChild<QPushButton *>("bodyRemove_PlanetarySpiceKernelName")->click(); tabs=panel->findChild<QTabWidget *>("bodyPages"); tabs->setCurrentIndex(2); auto *defaultFrames=panel->findChild<QListWidget *>("body_FrameSpiceKernelName"); require(defaultFrames && defaultFrames->count()>0,"Luna default FK list missing"); defaultFrames->selectAll(); panel->findChild<QPushButton *>("bodyRemove_FrameSpiceKernelName")->click(); apply(*panel); require(state("Luna").value("PlanetarySpiceKernelName").isEmpty() && state("Luna").value("FrameSpiceKernelName").isEmpty(),"Default PCK/FK removal retained startup membership"); require(window.saveScriptTo(saved) && window.loadScript(saved) && state("Luna").value("PlanetarySpiceKernelName").isEmpty() && state("Luna").value("FrameSpiceKernelName").isEmpty(),"Default kernel clear did not survive save/reopen");
      editor->setPlainText("Luna.PlanetarySpiceKernelName = { };\nLuna.FrameSpiceKernelName = {};\n"+original); require(window.buildScript() && state("Luna").value("PlanetarySpiceKernelName").isEmpty() && state("Luna").value("FrameSpiceKernelName").isEmpty(),"Separately written empty kernel lists did not clear startup defaults");
      close(window); editor->setPlainText(original); require(window.buildScript(),"Body Stop fixture restore failed"); panel=open(window,"Earth"); edit(*panel,"Mu")->setText("400000"); modal(*panel,[&] { panel->parentWidget()->close(); },[](QDialog *dialog) { auto *question=qobject_cast<QMessageBox *>(dialog); require(question,"Body close prompt missing"); question->button(QMessageBox::Cancel)->click(); }); require(panel->hasChanges() && editor->toPlainText()==original,"Body Close Cancel lost pending edits"); close(window);
      const QString loop="Create Variable n;\nBeginMissionSequence;\nWhile n < 1e12;\nn = n + 1;\nEndWhile;\n"; editor->setPlainText(loop); require(window.buildScript(),"Body loop fixture failed"); panel=open(window,"Earth"); bool guarded=false; QTimer::singleShot(20,&window,[&] { guarded=!panel->isEnabled() && !window.applyResourceChanges("Earth",{{"Mu","400000"}},loop).isEmpty(); window.stopMission(); }); require(window.runMission()==MainWindow::RunResult::Stopped && guarded && panel->isEnabled(),"Body editing not guarded during Run/Stop"); close(window); editor->setPlainText(original); require(window.runMission()==MainWindow::RunResult::Completed && bytes(report)==baselineReport,"Body mission did not recover after Stop");
      std::cout<<"Qt bodies: four wx pages, built-in protection, pending/Cancel/correction/rollback, physical reports, texture/model/pose/color rendering, comment-preserving repeated digit-prefixed properties, exact Undo/Redo, Unicode save/reopen, New Asteroid, SPICE orbit and custom-pole frame reports, PCK/FK selection/replacement/removal/order, startup kernel replacement/clear, independent scripts, invalid-ID/missing-SPK recovery and Run/Stop guards passed\n";
   } catch (BaseException &error) { std::cerr<<error.GetFullMessage()<<'\n'; return 1; } catch (const std::exception &error) { std::cerr<<error.what()<<'\n'; return 1; }
   return 0;
}
